### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by extsoft** [tatools/sunshine#16]
https://www.slf4j.org/
https://examples.javacodegeeks.com/enterprise-java/slf4j/slf4j-configuration-file-example/

**Comment by Mras** [comment]
Hi

Printing out test suite and summary gives some insight into what is going on, but there is a room for improvement:
* Printing out test suite is good for small number of test, in case of hundreds/thousands test scripts its less effective. I suggest printing out some statistics, like 'Found X tests in Y files, starting test execution...'
* Test execution can take quite a while. If it is remote execution you can not know if it hangs or actually executes some test and estimate time it will take. So the idea is to put some intermediate results into console. It can be really simple, like putting a dot for passed test, 'F' for failed 'S' for skipped. See [Dot Matrix](https://mochajs.org/#dot-matrix) reporter as an example.
* Adding some logging for debugging (visible only when DEBUG logging level is enabled). A few messages about main stages/methods that take place. Will help to quickly identify problems (hopefully without going into hardcore debug)

**Comment by Mras** [comment]
I see this implemented with inroduction of logging library plus JUnit/TestNG listeners

**Comment by extsoft** [comment]
@Mras 

> Printing out test suite is good for small number of test, in case of hundreds/thousands test scripts its less effective. I suggest printing out some statistics, like 'Found X tests in Y files, starting test execution...'

Partially agree. Will do some implementation and send a pull request.

> Adding some logging for debugging (visible only when DEBUG logging level is enabled). A few messages about main stages/methods that take place. Will help to quickly identify problems (hopefully without going into hardcore debug)

Agree, wait for a pull request. 

> Test execution can take quite a while. If it is remote execution you can not know if it hangs or actually executes some test and estimate time it will take. So the idea is to put some intermediate results into console. It can be really simple, like putting a dot for passed test, 'F' for failed 'S' for skipped. See Dot Matrix reporter as an example.

Disagree. The goal is to take clean XUNIT engine and run tests. The user is responsible for any desired reporting. Sunshine is responsible only for some common statistic and correct exit status (CI integration etc.).

**Comment by extsoft** [comment]
@Mras I updated some logging logic (see more on #117). And, I don't see any use case why we need to use some logger (just `System.out....`). So, please take a look through the changes and give your feedback.

**Comment by extsoft** [comment]
@Mras Anything else? If no, please close the issue.
