### ISSUE TITLE
.rultor.yml:10-10: Add ability to release to Sonatype

### ISSUE THREAD

**Issue by 0pdd** [tatools/sunshine#52]
The puzzle `49-7eb24613` in [`.rultor.yml`](https://github.com/tatools/sunshine/blob/master/.rultor.yml) (lines 10-10) has to be resolved: Add ability to release to Sonatype

The puzzle was created by Dmytro Serdiuk on 25-Apr-17. 

Estimate: 180 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by extsoft** [comment]
@rultor please release, the tag is `0.1.0-SNAPSHOT`.

**Comment by extsoft** [comment]
Second attempt.
@rultor please release, the tag is `0.1.0-SNAPSHOT`.

**Comment by extsoft** [comment]
@rultor please release, the tag is `0.1.0-SNAPSHOT`.

**Comment by 0pdd** [comment]
The puzzle `49-7eb24613` has disappeared from the source code, that's why I closed this issue.
