### ISSUE TITLE
SunshineJunit4.java:17-17: Add ability to generate junit xmls by...

### ISSUE THREAD

**Issue by 0pdd** [tatools/sunshine#62]
The puzzle `23-eb379235` in [`sunshine-junit4/src/main/java/io/github/tatools/sunshine/junit4/SunshineJunit4.java`](https://github.com/tatools/sunshine/blob/master/sunshine-junit4/src/main/java/io/github/tatools/sunshine/junit4/SunshineJunit4.java) (lines 17-17) has to be resolved: Add ability to generate junit xmls by default. Update javadoc in the class.

The puzzle was created by Dmytro Serdiuk on 28-Apr-17. 

Estimate: 120 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by extsoft** [comment]
Won't implement. Need to remove this puzzle.

**Comment by 0pdd** [comment]
The puzzle `23-eb379235` has disappeared from the source code, that's why I closed this issue.
