### ISSUE TITLE
Group classes into packages 

### ISSUE THREAD

**Issue by Mras** [tatools/sunshine#73]
Modules have one package that contains all classes. This makes hard to understand structure and finding need classes. Applicable for core module, maybe others if needed.

**Comment by extsoft** [comment]
@Mras We can do this before the first release. And it'll be hard to do as public API will be available. So, before an implementation, please describe which packages structure is desired for you.

**Comment by Mras** [comment]
@extsoft 
I would group classes by logical responsibilities: Classes that represent file system into one package, Classes that represent test/test suites into other, engine stuff to engine package, utils to utils, etc. Also suggest to leave in the root package only the most important stuff, like files with main methods (for example). 
The idea is to make it look neat and logical.

Other option is to separate classes and interfaces/abstractClasses, but i don't like this idea much.

**Comment by extsoft** [comment]
@Mras you reviewed the code. Are you still want to get some other packages structure? If yes, please write what you want to update otherwise close the issue.

**Comment by Mras** [comment]
@extsoft |I don't see any packages in any existing branch. Please let me know the branch/commit/pull request to look at.

**Comment by extsoft** [comment]
@Mras please take a look for the master branch.

**Comment by Mras** [comment]
@extsoft 
This is still a flat package structure. Am I missing something?
![image](https://user-images.githubusercontent.com/2988991/28768175-4f810d16-75df-11e7-8a60-e89e63adec73.png)

**Comment by extsoft** [comment]
@Mras yes, it's flat.

**Comment by Mras** [comment]
@extsoft so, in other words, you don't agree with this issue and want to keep it flat for now? If yes, lets close it for now.

**Comment by extsoft** [comment]
@Mras okay, will close.
